/**
 * easycron Scaffold Generator (Phase 3)
 *
 * Generates boilerplate code teaching the "Fast Endpoint" convention:
 *   - Express.js async endpoint with immediate 200 + background execution
 *   - Fastify async endpoint
 *   - Idempotency/rate-limiting middleware
 *   - Health endpoint
 *
 * These tutorials in code form help developers implement the API contract
 * that easycron external triggers expect.
 */

'use strict';

const fs = require('fs');
const path = require('path');

// ─── Express Scaffold ────────────────────────────────────────────

function generateExpressScaffold() {
  return `/**
 * easycron — Express.js "Fast Endpoint" Template
 *
 * This file demonstrates the API contract that easycron external triggers expect:
 *   1. Respond with 200 OK immediately (within <1 second)
 *   2. Execute the actual task asynchronously in the background
 *   3. Never let the task block the HTTP response
 *
 * Why? GitHub Actions / UptimeRobot have ~10s timeouts. If your task takes
 * 30s, the trigger will think it failed and retry — causing duplicate runs.
 *
 * Generated by: easycron scaffold
 */

const express = require('express');
const app = express();
const PORT = process.env.PORT || 3000;

// ─── In-Memory Execution Lock ────────────────────────────────────
// Prevents duplicate runs when retries or redundant triggers hit simultaneously.
// For production, replace with Redis or a database flag.

const executionLocks = new Map();

function isLocked(taskName) {
  const lastRun = executionLocks.get(taskName);
  if (!lastRun) return false;
  // 60-second cooldown window
  return (Date.now() - lastRun) < 60000;
}

function setLock(taskName) {
  executionLocks.set(taskName, Date.now());
}

// ─── Health Endpoint ─────────────────────────────────────────────
// Place BEFORE any auth middleware so monitoring can reach it.
// Used by: easycron keep-awake, UptimeRobot, health checks

app.get('/health', (req, res) => {
  res.status(200).json({
    status: 'ok',
    uptime: process.uptime(),
    timestamp: new Date().toISOString()
  });
});

// ─── Optional: API Key Middleware ────────────────────────────────
// Uncomment and set EASYCRON_API_KEY env variable to secure your endpoint.

/*
function requireAuth(req, res, next) {
  const key = req.headers['authorization'] || req.query.key;
  if (!key || key.replace('Bearer ', '') !== process.env.EASYCRON_API_KEY) {
    return res.status(403).json({ error: 'Unauthorized' });
  }
  next();
}
app.use('/api', requireAuth);
*/

// ─── Task Endpoint (The "Fast Endpoint" Pattern) ─────────────────
// This is the URL you give to easycron external:
//   easycron external https://your-app.com/api/task "every 10 minutes"

app.get('/api/task', (req, res) => {
  // Step 1: Check idempotency lock
  if (isLocked('my-task')) {
    console.log('[easycron] Task already running, skipping duplicate trigger');
    return res.status(200).json({ status: 'skipped', reason: 'cooldown' });
  }

  // Step 2: Respond IMMEDIATELY with 200 OK
  res.status(200).json({ status: 'accepted', message: 'Task started' });

  // Step 3: Execute the actual work AFTER responding
  setLock('my-task');
  runTaskAsync().catch(err => {
    console.error('[easycron] Task failed:', err.message);
  });
});

// ─── POST Variant ────────────────────────────────────────────────
// For triggers using: easycron external ... --method POST --body '{"action":"sync"}'

app.use(express.json());

app.post('/api/task', (req, res) => {
  const action = req.body?.action || 'default';

  if (isLocked(action)) {
    return res.status(200).json({ status: 'skipped', reason: 'cooldown' });
  }

  res.status(200).json({ status: 'accepted', action });

  setLock(action);
  runTaskAsync(action).catch(err => {
    console.error(\`[easycron] Task "\${action}" failed:\`, err.message);
  });
});

// ─── Your Actual Task Logic ──────────────────────────────────────
// Replace this with your real business logic.

async function runTaskAsync(action = 'default') {
  console.log(\`[easycron] Starting task: \${action} at \${new Date().toISOString()}\`);

  // Simulate work (replace with your actual task)
  await new Promise(resolve => setTimeout(resolve, 5000));

  console.log(\`[easycron] Task completed: \${action}\`);
}

// ─── Start Server ────────────────────────────────────────────────

app.listen(PORT, () => {
  console.log(\`[easycron] Server running on port \${PORT}\`);
  console.log(\`[easycron] Task endpoint: http://localhost:\${PORT}/api/task\`);
  console.log(\`[easycron] Health check:  http://localhost:\${PORT}/health\`);
});
`;
}

// ─── Fastify Scaffold ────────────────────────────────────────────

function generateFastifyScaffold() {
  return `/**
 * easycron — Fastify "Fast Endpoint" Template
 *
 * Same API contract as Express, but for Fastify users:
 *   1. Respond with 200 OK immediately
 *   2. Execute task asynchronously after response
 *   3. Idempotency lock to prevent duplicate runs
 *
 * Generated by: easycron scaffold
 */

const fastify = require('fastify')({ logger: true });
const PORT = process.env.PORT || 3000;

// ─── In-Memory Execution Lock ────────────────────────────────────

const executionLocks = new Map();

function isLocked(taskName) {
  const lastRun = executionLocks.get(taskName);
  if (!lastRun) return false;
  return (Date.now() - lastRun) < 60000;
}

function setLock(taskName) {
  executionLocks.set(taskName, Date.now());
}

// ─── Health Endpoint ─────────────────────────────────────────────

fastify.get('/health', async () => {
  return {
    status: 'ok',
    uptime: process.uptime(),
    timestamp: new Date().toISOString()
  };
});

// ─── Task Endpoint ───────────────────────────────────────────────

fastify.get('/api/task', async (request, reply) => {
  if (isLocked('my-task')) {
    return reply.code(200).send({ status: 'skipped', reason: 'cooldown' });
  }

  // Respond immediately
  reply.code(200).send({ status: 'accepted', message: 'Task started' });

  // Execute after response
  setLock('my-task');
  setImmediate(async () => {
    try {
      await runTaskAsync();
    } catch (err) {
      fastify.log.error(\`Task failed: \${err.message}\`);
    }
  });
});

// ─── POST Variant ────────────────────────────────────────────────

fastify.post('/api/task', async (request, reply) => {
  const action = request.body?.action || 'default';

  if (isLocked(action)) {
    return reply.code(200).send({ status: 'skipped', reason: 'cooldown' });
  }

  reply.code(200).send({ status: 'accepted', action });

  setLock(action);
  setImmediate(async () => {
    try {
      await runTaskAsync(action);
    } catch (err) {
      fastify.log.error(\`Task "\${action}" failed: \${err.message}\`);
    }
  });
});

// ─── Task Logic ──────────────────────────────────────────────────

async function runTaskAsync(action = 'default') {
  fastify.log.info(\`Starting task: \${action}\`);
  await new Promise(resolve => setTimeout(resolve, 5000));
  fastify.log.info(\`Task completed: \${action}\`);
}

// ─── Start ───────────────────────────────────────────────────────

fastify.listen({ port: PORT, host: '0.0.0.0' }, (err) => {
  if (err) {
    fastify.log.error(err);
    process.exit(1);
  }
});
`;
}

// ─── Scaffold Writer ─────────────────────────────────────────────

/**
 * Write the scaffold file to disk.
 * @param {{ framework: string, outputDir: string, filename: string|null }} options
 * @returns {{ filePath: string, framework: string }}
 */
function writeScaffold({ framework = 'express', outputDir = '.', filename = null }) {
  const defaultNames = {
    express: 'easycron-endpoint.js',
    fastify: 'easycron-endpoint.js',
  };

  const generators = {
    express: generateExpressScaffold,
    fastify: generateFastifyScaffold,
  };

  if (!generators[framework]) {
    throw new Error(`Unsupported framework: ${framework}. Supported: express, fastify`);
  }

  const targetFilename = filename || defaultNames[framework];
  const filePath = path.join(outputDir, targetFilename);

  // Collision safety
  if (fs.existsSync(filePath)) {
    throw new Error(
      `File already exists: ${filePath}\n` +
      `  Rename or delete it first, or use --filename to specify a different name.`
    );
  }

  const content = generators[framework]();
  fs.writeFileSync(filePath, content, 'utf-8');

  return { filePath, framework };
}

// ─── Exports ─────────────────────────────────────────────────────

module.exports = {
  generateExpressScaffold,
  generateFastifyScaffold,
  writeScaffold,
};
