/**
 * easycron Trigger Generator
 * Generates external trigger configurations:
 *   - GitHub Actions YAML with smart retry
 *   - UptimeRobot config (text output)
 *
 * Handles:
 *   - Auth header injection
 *   - YAML overwrite collision safety
 *   - Smart 3x retry with 10s backoff
 *   - Differentiation between timeout and 5xx errors
 */

'use strict';

const fs = require('fs');
const path = require('path');
const chalk = require('chalk');

// ─── GitHub Actions Generator ────────────────────────────────────

/**
 * Generate a GitHub Actions workflow YAML file.
 * @param {{ url: string, cron: string, auth: string|null, outputDir: string }} options
 * @returns {string} Path to the generated file
 */
function generateGitHubAction({ url, cron, auth, outputDir }) {
  const workflowDir = path.join(outputDir, '.github', 'workflows');

  // Ensure directory exists
  fs.mkdirSync(workflowDir, { recursive: true });

  // Collision safety: if file exists, increment the name
  let filename = 'easycron-trigger.yml';
  let filePath = path.join(workflowDir, filename);
  let counter = 2;

  while (fs.existsSync(filePath)) {
    filename = `easycron-trigger-${counter}.yml`;
    filePath = path.join(workflowDir, filename);
    counter++;
  }

  // Build curl command with optional auth
  let curlCmd = `curl -s -o /dev/null -w "%{http_code}" -m 10 -f`;
  if (auth) {
    curlCmd += ` -H "Authorization: ${auth}"`;
  }
  curlCmd += ` "${url}"`;

  // YAML content with smart retry logic
  // The bash script differentiates between:
  //   - Timeout/connection errors (retry)
  //   - 5xx server errors (fail immediately)
  //   - 2xx success (break)
  //
  // NOTE: We avoid template literals for the bash body to prevent
  // JS from eating bash $VARIABLE references.
  const yaml = [
    '# Generated by easycron — https://github.com/easycron/cli',
    '# Schedule: ' + cron,
    '# Target: ' + url,
    '#',
    '# ⚠️ GitHub Actions schedules use UTC time.',
    '# ⚠️ Intervals < 5 min may exhaust free tier quickly (2000 min/month).',
    '',
    'name: easycron-trigger',
    'on:',
    '  schedule:',
    '    - cron: "' + cron + '"',
    '  workflow_dispatch: {} # Allow manual trigger for testing',
    '',
    'jobs:',
    '  trigger:',
    '    runs-on: ubuntu-latest',
    '    steps:',
    '      - name: Hit Endpoint with Smart Retry',
    '        run: |',
    '          MAX_RETRIES=3',
    '          RETRY_DELAY=10',
    '          TIMEOUT=10',
    '          ',
    '          for i in $(seq 1 $MAX_RETRIES); do',
    '            echo "Attempt $i/$MAX_RETRIES..."',
    '            ',
    '            HTTP_CODE=$(' + curlCmd + ') || true',
    '            ',
    '            # Success',
    '            if [ "$HTTP_CODE" -ge 200 ] 2>/dev/null && [ "$HTTP_CODE" -lt 300 ] 2>/dev/null; then',
    '              echo "✔ Success (HTTP $HTTP_CODE)"',
    '              exit 0',
    '            fi',
    '            ',
    '            # 5xx = server error, fail immediately (don\'t retry app crashes)',
    '            if [ "$HTTP_CODE" -ge 500 ] 2>/dev/null && [ "$HTTP_CODE" -lt 600 ] 2>/dev/null; then',
    '              echo "✖ Server error (HTTP $HTTP_CODE) — not retrying"',
    '              exit 1',
    '            fi',
    '            ',
    '            # Timeout or connection refused = server likely cold-starting',
    '            if [ $i -lt $MAX_RETRIES ]; then',
    '              echo "⏳ Request failed (HTTP $HTTP_CODE), retrying in ${RETRY_DELAY}s..."',
    '              sleep $RETRY_DELAY',
    '            fi',
    '          done',
    '          ',
    '          echo "✖ All $MAX_RETRIES attempts failed"',
    '          exit 1',
    '',
  ].join('\n');

  fs.writeFileSync(filePath, yaml, 'utf-8');
  return filePath;
}

// ─── UptimeRobot Config Generator ────────────────────────────────

/**
 * Generate an UptimeRobot configuration string.
 * @param {{ url: string, intervalMinutes: number, auth: string|null }} options
 * @returns {string} Configuration instructions
 */
function generateUptimeRobotConfig({ url, intervalMinutes, auth }) {
  const interval = Math.max(intervalMinutes, 5); // UptimeRobot minimum is 5 min on free tier

  let config = `
  ┌─────────────────────────────────────────────────┐
  │           UptimeRobot Configuration             │
  ├─────────────────────────────────────────────────┤
  │  Monitor Type:    HTTP(s)                       │
  │  URL:             ${url.padEnd(30)}│
  │  Interval:        ${String(interval).padEnd(30)}│
  │  Monitoring Type: Keyword                       │
  │  Keyword:         OK                            │`;

  if (auth) {
    config += `
  │  HTTP Headers:                                  │
  │    Authorization: ${auth.padEnd(30)}│`;
  }

  config += `
  ├─────────────────────────────────────────────────┤
  │  Setup: https://uptimerobot.com/dashboard       │
  │  Create a new HTTP(s) monitor with the above.   │
  └─────────────────────────────────────────────────┘
`;

  return config;
}

// ─── Exports ─────────────────────────────────────────────────────

module.exports = { generateGitHubAction, generateUptimeRobotConfig };
