/**
 * easycron Trigger Generator
 * Generates external trigger configurations:
 *   - GitHub Actions YAML with smart retry
 *   - UptimeRobot config (text output)
 *   - cron-job.org config (text output)
 *   - Keep-awake helper configs
 *
 * Phase 2 additions:
 *   - cron-job.org provider support
 *   - Full redundancy mode (all 3 providers)
 *   - Configurable retry count and delay
 *   - HTTP method + body support for POST triggers
 *   - Keep-awake /health endpoint scaffolding
 *
 * Handles:
 *   - Auth header injection
 *   - YAML overwrite collision safety
 *   - Smart 3x retry with 10s backoff (configurable)
 *   - Differentiation between timeout and 5xx errors
 */

'use strict';

const fs = require('fs');
const path = require('path');

// ─── GitHub Actions Generator ────────────────────────────────────

/**
 * Generate a GitHub Actions workflow YAML file.
 * @param {{ url: string, cron: string, auth: string|null, outputDir: string, retries: number, delay: number, method: string, body: string|null }} options
 * @returns {string} Path to the generated file
 */
function generateGitHubAction({ url, cron, auth, outputDir, retries = 3, delay = 10, method = 'GET', body = null }) {
  const workflowDir = path.join(outputDir, '.github', 'workflows');

  // Ensure directory exists
  fs.mkdirSync(workflowDir, { recursive: true });

  // Collision safety: if file exists, increment the name
  let filename = 'easycron-trigger.yml';
  let filePath = path.join(workflowDir, filename);
  let counter = 2;

  while (fs.existsSync(filePath)) {
    filename = `easycron-trigger-${counter}.yml`;
    filePath = path.join(workflowDir, filename);
    counter++;
  }

  // Build curl command with optional auth, method, and body
  let curlCmd = 'curl -s -L -o /dev/null -w "%{http_code}" -m $TIMEOUT';
  if (method === 'POST') {
    curlCmd += ' -X POST';
    curlCmd += ' -H "Content-Type: application/json"';
    if (body) {
      curlCmd += " -d '" + body + "'";
    }
  }
  if (auth) {
    curlCmd += ' -H "Authorization: ' + auth + '"';
  }
  curlCmd += ' "' + url + '"';

  // YAML content with hardened retry logic
  // NOTE: We use string concatenation to avoid JS eating bash $VARIABLE references
  //
  // Robustness features:
  //   - curl -L follows redirects (prevents 3xx false-failures)
  //   - 30s timeout (free-tier cold starts can take 20-25s)
  //   - 2xx AND 3xx treated as success
  //   - 5xx retried (cold-start often causes transient 502/503)
  //   - 4xx fails immediately (misconfigured URL/auth)
  //   - Timeout/connection-refused retried (server booting)
  const yaml = [
    '# Generated by easycron CLI — https://github.com/namanjain24-sudo/easycron',
    '# Schedule: ' + cron,
    '# Target: ' + url,
    '# Method: ' + method,
    '#',
    '# ⚠️ GitHub Actions schedules use UTC time.',
    '# ⚠️ Intervals < 5 min may exhaust free tier quickly (2000 min/month).',
    '#',
    '# 💡 Retry config: MAX_RETRIES=' + retries + ', RETRY_DELAY=' + delay + 's',
    '#    Edit these values below if your server needs more boot time.',
    '',
    'name: easycron-trigger',
    'on:',
    '  schedule:',
    '    - cron: "' + cron + '"',
    '  workflow_dispatch: {} # Allow manual trigger for testing',
    '',
    'jobs:',
    '  trigger:',
    '    runs-on: ubuntu-latest',
    '    steps:',
    '      - name: Hit Endpoint with Smart Retry',
    '        run: |',
    '          MAX_RETRIES=' + retries,
    '          RETRY_DELAY=' + delay,
    '          TIMEOUT=30',
    '          ',
    '          for i in $(seq 1 $MAX_RETRIES); do',
    '            echo "Attempt $i/$MAX_RETRIES..."',
    '            ',
    '            HTTP_CODE=$(' + curlCmd + ') || true',
    '            ',
    '            # Success (2xx or 3xx — redirects are normal)',
    '            if [ "$HTTP_CODE" -ge 200 ] 2>/dev/null && [ "$HTTP_CODE" -lt 400 ] 2>/dev/null; then',
    '              echo "✔ Success (HTTP $HTTP_CODE)"',
    '              exit 0',
    '            fi',
    '            ',
    '            # 4xx = client error, fail immediately (bad URL/auth — retrying won\'t help)',
    '            if [ "$HTTP_CODE" -ge 400 ] 2>/dev/null && [ "$HTTP_CODE" -lt 500 ] 2>/dev/null; then',
    '              echo "✖ Client error (HTTP $HTTP_CODE) — check URL/auth"',
    '              exit 1',
    '            fi',
    '            ',
    '            # 5xx or timeout = server likely cold-starting, retry',
    '            if [ $i -lt $MAX_RETRIES ]; then',
    '              echo "⏳ Server not ready (HTTP $HTTP_CODE), retrying in ${RETRY_DELAY}s..."',
    '              sleep $RETRY_DELAY',
    '            fi',
    '          done',
    '          ',
    '          echo "✖ All $MAX_RETRIES attempts failed"',
    '          exit 1',
    '',
  ].join('\n');

  fs.writeFileSync(filePath, yaml, 'utf-8');
  return filePath;
}

// ─── UptimeRobot Config Generator ────────────────────────────────

/**
 * Generate an UptimeRobot configuration string.
 * @param {{ url: string, intervalMinutes: number, auth: string|null }} options
 * @returns {string} Configuration instructions
 */
function generateUptimeRobotConfig({ url, intervalMinutes, auth }) {
  const interval = Math.max(intervalMinutes, 5); // UptimeRobot minimum is 5 min on free tier

  const lines = [
    '',
    '  ┌──────────────────────────────────────────────────────┐',
    '  │            UptimeRobot Configuration                 │',
    '  ├──────────────────────────────────────────────────────┤',
    '  │  Monitor Type:    HTTP(s)                            │',
    '  │  URL:             ' + url.substring(0, 35).padEnd(35) + '│',
    '  │  Interval:        Every ' + (interval + ' min').padEnd(29) + '│',
    '  │  Monitoring Type: Keyword                            │',
    '  │  Keyword:         OK                                 │',
  ];

  if (auth) {
    lines.push('  │  HTTP Headers:                                       │');
    lines.push('  │    Authorization: ' + auth.substring(0, 35).padEnd(35) + '│');
  }

  lines.push('  ├──────────────────────────────────────────────────────┤');
  lines.push('  │  Setup Steps:                                        │');
  lines.push('  │  1. Go to https://uptimerobot.com/dashboard          │');
  lines.push('  │  2. Click "+ Add New Monitor"                        │');
  lines.push('  │  3. Enter the values above                           │');
  lines.push('  │  4. Save — done!                                     │');
  lines.push('  └──────────────────────────────────────────────────────┘');
  lines.push('');

  return lines.join('\n');
}

// ─── cron-job.org Config Generator ───────────────────────────────

/**
 * Generate a cron-job.org configuration string.
 * @param {{ url: string, cron: string, auth: string|null }} options
 * @returns {string} Configuration instructions
 */
function generateCronJobOrgConfig({ url, cron, auth }) {
  const lines = [
    '',
    '  ┌──────────────────────────────────────────────────────┐',
    '  │           cron-job.org Configuration                 │',
    '  ├──────────────────────────────────────────────────────┤',
    '  │  URL:             ' + url.substring(0, 35).padEnd(35) + '│',
    '  │  Schedule (cron): ' + cron.padEnd(35) + '│',
    '  │  Timezone:        UTC                                │',
    '  │  Request Method:  GET                                │',
    '  │  Timeout:         30 seconds                         │',
    '  │  Notifications:   On failure                         │',
  ];

  if (auth) {
    lines.push('  │                                                      │');
    lines.push('  │  Custom Headers:                                     │');
    lines.push('  │    Authorization: ' + auth.substring(0, 35).padEnd(35) + '│');
  }

  lines.push('  ├──────────────────────────────────────────────────────┤');
  lines.push('  │  Setup Steps:                                        │');
  lines.push('  │  1. Go to https://cron-job.org                       │');
  lines.push('  │  2. Create free account                              │');
  lines.push('  │  3. Click "CREATE CRONJOB"                           │');
  lines.push('  │  4. Paste the URL and cron expression above          │');
  lines.push('  │  5. Set timezone to UTC                              │');
  lines.push('  │  6. Save — done!                                     │');
  lines.push('  └──────────────────────────────────────────────────────┘');
  lines.push('');

  return lines.join('\n');
}

// ─── Keep-Awake Config Generator ──────────────────────────────────

/**
 * Generate keep-awake configurations:
 *  - A /health endpoint code snippet
 *  - A GitHub Action pinging every 14 min
 *  - An UptimeRobot config pinging every 5 min
 *
 * @param {{ url: string, outputDir: string, auth: string|null, framework: string }} options
 * @returns {{ healthSnippet: string, githubPath: string|null, uptimeConfig: string }}
 */
function generateKeepAwake({ url, outputDir, auth = null, framework = 'express' }) {
  // 1. Health endpoint code snippet
  let healthSnippet;
  if (framework === 'express') {
    healthSnippet = [
      '// Add this to your Express app to enable keep-awake pings',
      '// Place BEFORE any auth middleware so it responds without authentication',
      '',
      "app.get('/health', (req, res) => {",
      "  res.status(200).json({",
      "    status: 'ok',",
      "    uptime: process.uptime(),",
      "    timestamp: new Date().toISOString()",
      '  });',
      '});',
    ].join('\n');
  } else if (framework === 'fastify') {
    healthSnippet = [
      '// Add this to your Fastify app to enable keep-awake pings',
      '',
      "fastify.get('/health', async (request, reply) => {",
      '  return {',
      "    status: 'ok',",
      '    uptime: process.uptime(),',
      '    timestamp: new Date().toISOString()',
      '  };',
      '});',
    ].join('\n');
  } else {
    // Generic
    healthSnippet = [
      '// Add a /health endpoint to your server',
      '// It must respond with 200 OK instantly',
      '// Place BEFORE any auth middleware',
      '',
      '// GET /health → { "status": "ok" }',
    ].join('\n');
  }

  // 2. GitHub Action for keep-awake (14 min interval)
  const healthUrl = url.replace(/\/+$/, '') + '/health';

  const githubPath = generateGitHubAction({
    url: healthUrl,
    cron: '*/14 * * * *', // Every 14 min — just under the 15 min sleep threshold
    auth: null,           // Health endpoint should not need auth
    outputDir,
    retries: 2,
    delay: 5,
    method: 'GET',
    body: null,
  });

  // 3. UptimeRobot config for keep-awake
  const uptimeConfig = generateUptimeRobotConfig({
    url: healthUrl,
    intervalMinutes: 5,
    auth: null,
  });

  return { healthSnippet, githubPath, uptimeConfig };
}

// ─── Exports ─────────────────────────────────────────────────────

module.exports = {
  generateGitHubAction,
  generateUptimeRobotConfig,
  generateCronJobOrgConfig,
  generateKeepAwake,
};
